version: '3.3'

services:
  #mongo:
  #  image: mongo
  #  container_name: mongo-docker
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: mongoadmin
  #    MONGO_INITDB_ROOT_PASSWORD: mongoadmin
  #  ports:
  #    - '27017:27017'
  #  volumes:
  #    - type: volume
  #      source: mongodb_data_volume
  #      target: /data/db

  gateway-microservice:
    build:
      context: ./gateway-microservice
    ports:
      - 3000:3000
    environment:
      - AUTH_SERVICE_URL=http://auth-microservice:3001/auth
      - USER_SERVICE_URL=http://user-microservice:3002/users
      - BOOKING_SERVICE_URL=http://booking-microservice:3003/bookings
      - SPORTS_VENUE_SERVICE_URL=http://sports-venue-microservice:3004/sports-venues
      - FEED_SERVICE_URL=http://sports-venue-microservice:3004/posts

  auth-microservice:
    build:
      context: ./auth-microservice
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb+srv://field4youadmin:field4youpass@field4you-cluster.sktb0.mongodb.net/auth-microservice?retryWrites=true&w=majority&appName=field4you-cluster
      - JWT_SECRET=field4you2024
      - MAIL_ACCOUNT=field4youapi@gmail.com
      - MAIL_PASSWORD=smrazgjluryzsbgp
      - USER_GATEWAY_SERVICE_URL=http://gateway-microservice:3000/api/users
    depends_on:
      - gateway-microservice

  user-microservice:
    build:
      context: ./user-microservice
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb+srv://field4youadmin:field4youpass@field4you-cluster.sktb0.mongodb.net/user-microservice?retryWrites=true&w=majority&appName=field4you-cluster
      - AUTH_GATEWAY_SERVICE_URL=http://gateway-microservice:3000/api/auth
    depends_on:
      - gateway-microservice

  booking-microservice:
    build:
      context: ./booking-microservice
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb+srv://field4youadmin:field4youpass@field4you-cluster.sktb0.mongodb.net/booking-microservice?retryWrites=true&w=majority&appName=field4you-cluster
    depends_on:
      - gateway-microservice

  sports-venue-microservice:
    build:
      context: ./sports-venue-microservice
    ports:
      - 3004:3004
    environment:
      - PORT=3004
      - MONGODB_URI=mongodb+srv://field4youadmin:field4youpass@field4you-cluster.sktb0.mongodb.net/sports-venue-microservice?retryWrites=true&w=majority&appName=field4you-cluster
    depends_on:
      - gateway-microservice

  feed-microservice:
    build:
      context: ./feed-microservice
    ports:
      - 3005:3005
    environment:
      - PORT=3005
      - MONGODB_URI=mongodb+srv://field4youadmin:field4youpass@field4you-cluster.sktb0.mongodb.net/feed-microservice?retryWrites=true&w=majority&appName=field4you-cluster
    depends_on:
      - gateway-microservice
#volumes:
#  mongodb_data_volume:
#    driver: local
